version: "3.9"
services:
    web:
        build: ./todo-app/
        ports:
            - 8080:8080
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=todoappuser
            - MONGO_INITDB_ROOT_PASSWORD=password123