version: "3.9"
services:
    api:
        build: ./api/
        ports:
            - 8080:8080
        depends_on:
            - mongo
    ui:
        build: ./ui/
        ports:
            - 3000:3000
        depends_on:
            - api
    mongo:
        image: mongo:latest
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=todoappuser
            - MONGO_INITDB_ROOT_PASSWORD=password123
